// Generated by https://quicktype.io
export interface Country {
  country: string;
}

export interface MapCountry {
  countryList: Country;
} // Generated by https://quicktype.io

export interface All {
  confirmed: number;
  recovered: number;
  deaths: number;
  country: string;
  population: number;
  sq_km_area: number;
  life_expectancy: string;
  elevation_in_meters: null;
  continent: string;
  abbreviation: string;
  location: string;
  iso: number;
  capital_city: string;
  lat: string;
  long: string;
  updated: string;
}
